#AKQJT
#AKQJT

range1 = ['A','K','Q','J','T']


AK  = 'AK'; AQ = 'AQ'; AJ='AJ'; AT='AT'; KA='KA'; KQ='KQ'; KJ='KJ'; KT='KT'; 
QA='QA'; QK='QK'; QJ='QJ'; QT='QT'; JA='JA'; JK='JK'; JQ='JQ'; JT='JT'; 
TA='TA'; TK='TK'; TQ='TQ'; TJ='TJ'

CARDS_DEALINGS = [AK,AQ,AJ,AT,KA,KQ,KJ,KT, QA, QK, QJ, QT, JA, JK, JQ, JT, TA, TK, TQ, TJ]

CHANCE = "CHANCE"
CHECK = "CHECK"
CALL = "CALL"
FOLD = "FOLD"
BET = "BET"

#optomized for the OOP Player
RESULTS_MAP = {}
RESULTS_MAP[AK] = 1
RESULTS_MAP[AQ] = 1
RESULTS_MAP[AJ] = 1
RESULTS_MAP[AT] = 1
RESULTS_MAP[KA] = -1
RESULTS_MAP[KQ] = 1
RESULTS_MAP[KJ] = 1
RESULTS_MAP[KT] = 1
RESULTS_MAP[QA] = -1
RESULTS_MAP[QK] = -1
RESULTS_MAP[QJ] = 1
RESULTS_MAP[QT] = 1
RESULTS_MAP[JA] = -1
RESULTS_MAP[JK] = -1
RESULTS_MAP[JQ] = -1
RESULTS_MAP[JT] = 1
RESULTS_MAP[TA] = -1
RESULTS_MAP[TK] = -1
RESULTS_MAP[TQ] = -1
RESULTS_MAP[TJ] = -1


A = 1
B = -A
